org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official
kotlin.version=2.1.21
compose.version=1.8.2
agp.version=8.7.3
kotlinx.serialization.version=1.7.3
okio.version=3.9.1
webview.version=2.0.3
kotlin.mpp.applyDefaultHierarchyTemplate=false
android.useAndroidX=true
android.nonTransitiveRClass=true
