/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UnitConverterDialog.java
 *
 * Created on Oct 23, 2009, 9:37:36 AM
 */
package recipejar;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;

import javax.swing.DefaultComboBoxModel;

import recipejar.recipe.Unit;

/**
 *
 * @author james
 */
public class UnitConverterDialog extends javax.swing.JDialog {

	private HashMap<String, DefaultComboBoxModel> toComboBoxModels;

	private DefaultComboBoxModel getComboBoxModelFor(String u) {
		if (toComboBoxModels.containsKey(u)) {
			return toComboBoxModels.get(u);
		} else {

			if (Unit.getUnit(u).hasConversionUnits()) {
				DefaultComboBoxModel m = new DefaultComboBoxModel(Unit.getUnit(u).getConversionUnitKeySet().toArray());
				toComboBoxModels.put(u, m);
				return m;
			} else {
				DefaultComboBoxModel m = new DefaultComboBoxModel(new String[0]);
				toComboBoxModels.put(u, m);
				return m;
			}
		}
	}

	private ActionListener fromListnr = new ActionListener() {

		public void actionPerformed(ActionEvent e) {
			toUnts.setModel(getComboBoxModelFor(fromUnts.getSelectedItem().toString()));
//			if (fromUnts.getSelectedIndex() >= 0) {
//				toUnts.removeActionListener(toListnr);
//				toUnts.removeAllItems();
			//// toUnts.addItem("Convert To...");
			// Set<String> keys =
			//// units.get(fromUnts.getSelectedIndex()).getConversionUnitKeySet();
			// for (Iterator<String> i = keys.iterator(); i.hasNext();) {
			// toUnts.addItem(i.next());
			// }
			// toUnts.addActionListener(toListnr);
			// }
		}
	};
	private ActionListener toListnr = new ActionListener() {

		public void actionPerformed(ActionEvent e) {
			if (!toUnts.getSelectedItem().toString().equals("Convert To...")) {
				/*
				 * if (quantity.getText().contains("+") || quantity.getText().contains("-") ||
				 * quantity.getText().contains("*") || quantity.getText().contains("/") ||
				 * quantity.getText().contains("(") || quantity.getText().contains(")")) {
				 * quantity.setText(decimalToFraction(Float.parseFloat(quantity.getText()))); }
				 */
				quantity.setText(Unit.convert(quantity.getText(), Unit.getUnit(fromUnts.getSelectedItem().toString()),
						Unit.getUnit(toUnts.getSelectedItem().toString())));
				quantity.selectAll();
				// toUnts.setSelectedIndex(0);
			}
		}
	};

	/**
	 * Creates new form UnitConverterDialog
	 * 
	 * @param parent
	 * @param modal
	 */
	public UnitConverterDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();

		toComboBoxModels = new HashMap<String, DefaultComboBoxModel>();

		this.fromUnts.addActionListener(fromListnr);
		this.toUnts.addActionListener(toListnr);
		quantity.addActionListener(toListnr);
	}

	/*
	 * public void reloadUnits(ArrayList<Unit> u) {
	 * fromUnts.removeActionListener(fromListnr);
	 * toUnts.removeActionListener(toListnr); fromUnts.removeAllItems();
	 * toUnts.removeAllItems(); toUnts.addItem("Convert To..."); units = new
	 * ArrayList<Unit>(); for (Iterator<Unit> i = u.iterator(); i.hasNext();) { Unit
	 * temp = i.next(); if (temp.isConvertable()) { units.add(temp);
	 * fromUnts.addItem(temp.getPlural()); } } toUnts.removeAllItems();
	 * toUnts.addItem("Convert To..."); Set<String> keys =
	 * units.get(fromUnts.getSelectedIndex()).getConversionUnitKeySet(); for
	 * (Iterator<String> i = keys.iterator(); i.hasNext();) {
	 * toUnts.addItem(i.next()); }
	 * 
	 * fromUnts.addActionListener(fromListnr); toUnts.addActionListener(toListnr); }
	 */

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		quantity = new javax.swing.JTextField();
		fromUnts = new javax.swing.JComboBox();
		toUnts = new javax.swing.JComboBox();

		setTitle("Unit Converter");

		quantity.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				quantityKeyPressed(evt);
			}
		});

		fromUnts.setModel(new javax.swing.DefaultComboBoxModel(Unit.getConvertableUnitLabels()));
		fromUnts.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				convertableUntsKeyPressed(evt);
			}
		});

		toUnts.setModel(new javax.swing.DefaultComboBoxModel(
				Unit.getUnit(fromUnts.getSelectedItem().toString()).getConversionUnitKeySet().toArray()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addComponent(quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(fromUnts, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addComponent(toUnts, 0, 300, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(fromUnts, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(toUnts,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void convertableUntsKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_convertableUntsKeyPressed
		shortcutHandler(evt);
	}// GEN-LAST:event_convertableUntsKeyPressed

	private void quantityKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_quantityKeyPressed
		shortcutHandler(evt);
	}

	private void shortcutHandler(java.awt.event.KeyEvent evt) {
		// if (recipejar.Util.isOS("mac")) {
		// if (evt.isMetaDown()) {
		// if (evt.getKeyCode() == KeyEvent.VK_W) {
		// this.setVisible(false);
		// }
		// }
		// }
	}// GEN-LAST:event_quantityKeyPressed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox fromUnts;
	private javax.swing.JTextField quantity;
	private javax.swing.JComboBox toUnts;
	// End of variables declaration//GEN-END:variables
}
